### PR TITLE
Add minimum date of a day and default date of a week

### PR DESCRIPTION
**Pull request by summer-cook**
# Summary
- The datepicker in the additional info component will now have a minimum date of one day
- The default date when a user opens the date picker will now be one week

# Video
https://share.getcloudapp.com/4gu4eyL0

### CODE REVIEW

**Review by alishaevn — CHANGES_REQUESTED** [review]
the video shows that the date picker is now in `DD/MM/YYYY` format. can we switch that back to `MM/DD/YYYY`?

**Comment by summer-cook** [comment]
> the video shows that the date picker is now in `DD/MM/YYYY` format. can we switch that back to `MM/DD/YYYY`?

i think it was always DD/MM/YYYY. I just switched back to main to check and it is the same:
image

i looked into how to change the format, and tried several things but its not as straightforward as i thought it would be. i can look into it more but it has not been changed in this ticket

**Comment by summer-cook** [comment]
@alishaevn 

Just looked into it more and because it uses the normal HTML5 date input, its likely based on operating system

https://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format

if you read the first answer under "presentation format" - possibly because my devices are in spanish or i am in mexico it is showing me the correct date format for mexico, while it shows you the format thats used in the states. which is why it is a discrepancy between what you see and my video.

**Comment by alishaevn** [comment]
>  possibly because my devices are in spanish/my browsers language is set to spanish, or i am in mexico it is showing me the correct date format for mexico, while it shows you the format thats used in the states. which is why it is a discrepancy between what you see and my video.

ahh, good sleuthing! because my app def shows `MM/DD/YYYY`. 😄

**Review by alishaevn — APPROVED** [review]

**Pull request merged**
